export const currencies: Record<string, { symbols: string[]; name: string }> = {
  AED: { symbols: ['د.إ', 'dirham'], name: 'United Arab Emirates dirham' },
  AFN: { symbols: ['؋'], name: 'Afghanistan Afghani' },
  ALL: { symbols: ['lek'], name: 'Albania Lek' },
  AMD: { symbols: [], name: 'Armenian Dram' },
  ANG: { symbols: ['ƒ'], name: 'Netherlands Antilles Guilder' },
  AOA: { symbols: [], name: 'Angola Kwanza' },
  ARS: { symbols: ['ar$'], name: 'Argentina Peso' },
  AUD: { symbols: ['au$'], name: 'Australia Dollar' },
  AWG: { symbols: ['ƒ'], name: 'Aruba Guilder' },
  AZN: { symbols: ['ман'], name: 'Azerbaijan New Manat' },
  BAM: { symbols: ['km'], name: 'Bosnia and Herzegovina Convertible Marka' },
  BBD: { symbols: ['bb$'], name: 'Barbados Dollar' },
  BDT: { symbols: [], name: 'Bangladesh Taka' },
  BGN: { symbols: ['лв', 'lv'], name: 'Bulgaria Lev' },
  BHD: { symbols: [], name: 'Bahraini Dinar' },
  BIF: { symbols: [], name: 'Burundi Franc' },
  BMD: { symbols: [], name: 'Bermuda Dollar' },
  BND: { symbols: [], name: 'Brunei Darussalam Dollar' },
  BOB: { symbols: ['$b'], name: 'Bolivia Bolíviano' },
  BRL: { symbols: ['r$'], name: 'Brazil Real' },
  BSD: { symbols: ['bs$'], name: 'Bahamas Dollar' },
  BWP: { symbols: ['p'], name: 'Botswana Pula' },
  BYN: { symbols: ['br'], name: 'Belarus Ruble' },
  BZD: { symbols: ['bz$'], name: 'Belize Dollar' },
  CAD: { symbols: ['ca$'], name: 'Canada Dollar' },
  CDF: { symbols: [], name: 'Congolese Franc' },
  CHF: { symbols: [], name: 'Switzerland Franc' },
  CLP: { symbols: [], name: 'Chile Peso' },
  CNY: { symbols: [], name: 'China Yuan Renminbi' },
  COP: { symbols: [], name: 'Colombia Peso' },
  CRC: { symbols: ['₡'], name: 'Costa Rica Colon' },
  CUP: { symbols: ['₱'], name: 'Cuba Peso' },
  CZK: { symbols: ['kč'], name: 'Czech Republic Koruna' },
  DJF: { symbols: [], name: 'Djibouti Franc' },
  DKK: { symbols: ['dkr'], name: 'Denmark Krone' },
  DOP: { symbols: ['rd$'], name: 'Dominican Republic Peso' },
  DZD: { symbols: [], name: 'Algerian Dinar' },
  EGP: { symbols: ['£E', '￡E'], name: 'Egypt Pound' },
  ERN: { symbols: [], name: 'Nakfa' },
  ETB: { symbols: [], name: 'Ethiopian Birr' },
  EUR: { symbols: ['€'], name: 'Euro Member Countries' },
  FJD: { symbols: ['fj$'], name: 'Fiji Dollar' },
  FKP: { symbols: [], name: 'Falkland Islands (Malvinas) Pound' },
  GBP: { symbols: ['£', '￡'], name: 'United Kingdom Pound' },
  GEL: { symbols: [], name: 'Georgia Lari' },
  GGP: { symbols: [], name: 'Guernsey Pound' },
  GHS: { symbols: ['¢'], name: 'Ghana Cedi' },
  GIP: { symbols: [], name: 'Gibraltar Pound' },
  GMD: { symbols: [], name: 'Gambia Dalasi' },
  GNF: { symbols: [], name: 'Guinea Franc' },
  GTQ: { symbols: ['q'], name: 'Guatemala Quetzal' },
  GYD: { symbols: ['gy$'], name: 'Guyana Dollar' },
  HKD: { symbols: ['hk$'], name: 'Hong Kong Dollar' },
  HNL: { symbols: ['l'], name: 'Honduras Lempira' },
  HRK: { symbols: ['kn'], name: 'Croatia Kuna' },
  HUF: { symbols: ['ft'], name: 'Hungary Forint' },
  IDR: { symbols: ['rp'], name: 'Indonesia Rupiah' },
  ILS: { symbols: ['₪'], name: 'Israel Shekel' },
  IMP: { symbols: [], name: 'Isle of Man Pound' },
  INR: { symbols: ['rs'], name: 'India Rupee' },
  IQD: { symbols: [], name: 'Iraqi Dinar' },
  IRR: { symbols: ['﷼'], name: 'Iran Rial' },
  ISK: { symbols: [], name: 'Iceland Krona' },
  JEP: { symbols: [], name: 'Jersey Pound' },
  JMD: { symbols: ['j$'], name: 'Jamaica Dollar' },
  JOD: { symbols: [], name: 'Jordanian Dinar' },
  JPY: { symbols: ['¥', '¥', '円'], name: 'Japan Yen' },
  KES: { symbols: [], name: 'Kenyan Shilling' },
  KGS: { symbols: ['лв'], name: 'Kyrgyzstan Som' },
  KHR: { symbols: ['៛'], name: 'Cambodia Riel' },
  KMF: { symbols: [], name: 'Comoro Franc' },
  KPW: { symbols: ['₩'], name: 'Korea (North) Won' },
  KRW: { symbols: ['₩'], name: 'Korea (South) Won' },
  KWD: { symbols: [], name: 'Kuwaiti Dinar' },
  KYD: { symbols: ['ky$'], name: 'Cayman Islands Dollar' },
  KZT: { symbols: ['тг'], name: 'Kazakhstan Tenge' },
  LAK: { symbols: ['₭'], name: 'Laos Kip' },
  LBP: { symbols: [], name: 'Lebanon Pound' },
  LKR: { symbols: ['₨'], name: 'Sri Lanka Rupee' },
  LRD: { symbols: ['lr$'], name: 'Liberia Dollar' },
  LSL: { symbols: [], name: 'Lesotho Loti' },
  LYD: { symbols: [], name: 'Libyan Dinar' },
  MAD: { symbols: ['dh', 'dhs'], name: 'Moroccan Dirham' },
  MDL: { symbols: [], name: 'Moldovan Leu' },
  MGA: { symbols: [], name: 'Malagasy Ariary' },
  MKD: { symbols: ['ден'], name: 'Macedonia Denar' },
  MMK: { symbols: [], name: 'Myanmar Kyat' },
  MNT: { symbols: ['₮'], name: 'Mongolia Tughrik' },
  MOP: { symbols: [], name: 'Macao Pataca' },
  MRO: { symbols: [], name: 'Mauritania Ouguiya' },
  MUR: { symbols: ['₨'], name: 'Mauritius Rupee' },
  MVR: { symbols: [], name: 'Maldives Rufiyaa' },
  MWK: { symbols: [], name: 'Malawi Kwacha' },
  MXN: { symbols: [], name: 'Mexico Peso' },
  MYR: { symbols: ['rm'], name: 'Malaysia Ringgit' },
  MZN: { symbols: ['mt'], name: 'Mozambique Metical' },
  NAD: { symbols: ['na$'], name: 'Namibia Dollar' },
  NGN: { symbols: ['₦'], name: 'Nigeria Naira' },
  NIO: { symbols: ['c$'], name: 'Nicaragua Cordoba' },
  NOK: { symbols: [], name: 'Norway Krone' },
  NPR: { symbols: ['₨'], name: 'Nepal Rupee' },
  NZD: { symbols: ['nz$'], name: 'New Zealand Dollar' },
  OMR: { symbols: ['﷼'], name: 'Oman Rial' },
  PAB: { symbols: ['b/.'], name: 'Panama Balboa' },
  PEN: { symbols: ['s/.'], name: 'Peru Sol' },
  PGK: { symbols: [], name: 'Papua New Guinea Kina' },
  PHP: { symbols: ['₱'], name: 'Philippines Peso' },
  PKR: { symbols: ['₨'], name: 'Pakistan Rupee' },
  PLN: { symbols: ['zł'], name: 'Poland Zloty' },
  PYG: { symbols: ['gs'], name: 'Paraguay Guarani' },
  QAR: { symbols: ['﷼'], name: 'Qatar Riyal' },
  RON: { symbols: ['lei'], name: 'Romania New Leu' },
  RSD: { symbols: ['дин'], name: 'Serbia Dinar' },
  RUB: { symbols: ['₽'], name: 'Russia Ruble' },
  RWF: { symbols: [], name: 'Rwanda Franc' },
  SAR: { symbols: ['﷼'], name: 'Saudi Arabia Riyal' },
  SBD: { symbols: ['sb$'], name: 'Solomon Islands Dollar' },
  SCR: { symbols: ['₨'], name: 'Seychelles Rupee' },
  SDG: { symbols: [], name: 'Sudanese Pound' },
  SEK: { symbols: ['kr'], name: 'Sweden Krona' },
  SGD: { symbols: ['sg$'], name: 'Singapore Dollar' },
  SHP: { symbols: [], name: 'Saint Helena Pound' },
  SLL: { symbols: [], name: 'Sierra Leone' },
  SOS: { symbols: ['s'], name: 'Somalia Shilling' },
  SRD: { symbols: ['sr$'], name: 'Suriname Dollar' },
  SSP: { symbols: [], name: 'South Sudanese Pound' },
  STD: { symbols: [], name: 'Sao Tome and Principe Dobra' },
  SVC: { symbols: [], name: 'El Salvador Colon' },
  SYP: { symbols: [], name: 'Syria Pound' },
  SZL: { symbols: [], name: 'Swaziland Lilangeni' },
  THB: { symbols: ['฿'], name: 'Thailand Baht' },
  TJS: { symbols: [], name: 'Tajikistan Somoni' },
  TMT: { symbols: [], name: 'Turkmenistan New Manat' },
  TND: { symbols: [], name: 'Tunisian Dinar' },
  TRY: { symbols: [], name: 'Turkey Lira' },
  TTD: { symbols: ['tt$'], name: 'Trinidad and Tobago Dollar' },
  TVD: { symbols: ['tv$'], name: 'Tuvalu Dollar' },
  TWD: { symbols: ['nt$'], name: 'Taiwan New Dollar' },
  TZS: { symbols: [], name: 'Tanzanian Shilling' },
  UAH: { symbols: ['₴'], name: 'Ukraine Hryvnia' },
  UGX: { symbols: [], name: 'Uganda Shilling' },
  USD: { symbols: ['$', '﹩', '＄', 'us$'], name: 'United States Dollar' },
  UYU: { symbols: ['$u'], name: 'Uruguay Peso' },
  UZS: { symbols: ['лв'], name: 'Uzbekistan Som' },
  VEF: { symbols: ['bs'], name: 'Venezuela Bolivar' },
  VND: { symbols: ['₫'], name: 'Viet Nam Dong' },
  VUV: { symbols: [], name: 'Vanuatu Vatu' },
  WST: { symbols: [], name: 'Samoa Tala' },
  XAF: { symbols: [], name: 'Central African Franc' },
  XCD: { symbols: ['xc$'], name: 'East Caribbean Dollar' },
  XOF: { symbols: [], name: 'West African Franc' },
  XPF: { symbols: [], name: 'CFP Franc' },
  YER: { symbols: ['﷼'], name: 'Yemen Rial' },
  ZAR: { symbols: ['r'], name: 'South Africa Rand' },
  ZMW: { symbols: [], name: 'Zambian Kwacha' },
  ZWD: { symbols: ['z$'], name: 'Zimbabwe Dollar' },
  ZWL: { symbols: [], name: 'Zimbabwe Dollar' },
};
